name: Inception

services:

  mariadb:
    container_name: mariadb
    env_file: .env
    restart: unless-stopped
    build: 
      context: srcs/MariaDB
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes: 
      - mariadb:/usr/share/mariadb
    ports : 
      - "3307:3307"
    healthcheck:
      test: [ "CMD", "/bin/healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  adminer:
    container_name: adminer
    env_file: .env #TODO Check if necessary
    restart: unless-stopped
    build:
      context: srcs/Adminer
      dockerfile: Dockerfile  
    networks: 
      - inception
    depends_on:
      - mariadb
    ports : 
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    container_name: nginx
    env_file: .env #TODO Check if necessary
    restart: unless-stopped
    build: 
      context: srcs/NGinx
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes: 
      - wordpress-files:/usr/share/nginx
    depends_on: 
      - wordpress
    ports : 
      - "443:443"


  wordpress:
    container_name: wordpress
    env_file: .env
    restart: unless-stopped
    build: 
      context: srcs/WordPress
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes: 
      - wordpress-files:/usr/share/nginx
    depends_on:
      - mariadb
      - redis
    ports: 
      - "9000:9000"

  beszel:
    container_name: beszel
    restart: unless-stopped
    build: 
      context: srcs/Beszel
      dockerfile: Dockerfile
      target: server
    environment:
      - APP_URL=http://localhost:8090 #TODO remove
      - USER_EMAIL=admin@localhost.com
      - USER_PASSWORD=admin@localhost.com
    networks: 
      - inception
    ports: 
      - "8090:8090"
    healthcheck:
      test: ['CMD', './beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s

  beszel-agent:
    container_name: beszel-agent
    restart: unless-stopped
    build: 
      context: srcs/Beszel
      dockerfile: Dockerfile
      target: agent
    environment:
      - HUB_URL=http://beszel:8090 #TODO remove
      - ADMIN_EMAIL=admin@localhost.com
      - ADMIN_PASSWORD=admin@localhost.com
    networks: 
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ['CMD', './beszel-agent', 'health']
      interval: 120s

  redis:
    privileged: true
    container_name: redis
    restart: unless-stopped
    build:
      context: srcs/Redis
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "6379:6379"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lcamerly/data/mariadb
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lcamerly/data/wordpress-files
  
networks:
  inception:
    driver: bridge
