name: Inception

services:

  mariadb:
    container_name: mariadb
    env_file: .env
    restart: unless-stopped
    build: 
      context: srcs/MariaDB
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes: 
      - mariadb:/usr/share/mariadb
    healthcheck:
      test: [ "CMD-SHELL", "/bin/healthcheck.sh --connect --innodb_initialized" ]
      start_period: 5s
      interval: 30s
      retries: 3

  adminer:
    container_name: adminer
    restart: unless-stopped
    build:
      context: srcs/Adminer
      dockerfile: Dockerfile
      args:
        - ADMINER_VERSION=$ADMINER_VERSION
    networks: 
      - inception
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080"]
      start_period: 5s
      interval: 30s
      retries: 3

  nginx:
    container_name: nginx
    env_file: .env #TODO Check if necessary
    restart: unless-stopped
    build: 
      context: srcs/NGinx
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes: 
      - wordpress-files:/usr/share/nginx
    depends_on: 
      - wordpress
    ports : 
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -sk https://localhost/status"]
      start_period: 5s
      interval: 30s
      retries: 3


  wordpress:
    container_name: wordpress
    env_file: .env
    restart: unless-stopped
    build: 
      context: srcs/WordPress
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes: 
      - wordpress-files:/usr/share/nginx
    depends_on:
      - mariadb
      - redis
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -r \"php-fpm: master process\""]
      start_period: 5s
      interval: 30s
      retries: 3

  beszel:
    container_name: beszel
    restart: unless-stopped
    build: 
      context: srcs/Beszel
      dockerfile: Dockerfile
      target: server
    environment:
      - APP_URL=https://lcamerly.42.fr/beszel #TODO remove
      - USER_EMAIL=admin@localhost.com
      - USER_PASSWORD=admin@localhost.com
    networks: 
      - inception
    healthcheck:
      test: ['CMD-SHELL', "./beszel health --url http://localhost:8090"]
      start_period: 5s
      interval: 30s
      retries: 3

  beszel-agent:
    container_name: beszel-agent
    restart: unless-stopped
    hostname: InceptionCluster
    build: 
      context: srcs/Beszel
      dockerfile: Dockerfile
      target: agent
    environment:
      - HUB_URL=http://beszel:8090 #TODO remove
      - ADMIN_EMAIL=admin@localhost.com
      - ADMIN_PASSWORD=admin@localhost.com
    networks: 
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ['CMD-SHELL', "/beszel-agent health"]
      start_period: 5s
      interval: 30s
      retries: 3

  redis:
    privileged: true
    container_name: redis
    restart: unless-stopped
    build:
      context: srcs/Redis
      dockerfile: Dockerfile
    networks:
      - inception
    healthcheck:
      test: "[ $(redis-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 30s
      retries: 3

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lcamerly/data/mariadb
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lcamerly/data/wordpress-files
  
networks:
  inception:
    driver: bridge
